// =====================================================================
//  MAPPA SOTTOSTANTI  ·  SIGLA -> NOME ESTESO
//  Modifica solo questo file per aggiungere/correggere i nomi.
//  Le sigle non presenti qui restano mostrate come sigla nel sito.
//  Suggerimento: lancia export_markup_json.m per generare
//  sottostanti_template.js con l'elenco COMPLETO delle tue sigle.
// =====================================================================
window.SOTTOSTANTI = {

  "A2": "A2A",
  "AAL": "American Airlines",
  "AAPL": "Apple",
  "ABBV": "AbbVie",
  "ABI": "Anheuser-Busch InBev",
  "ABNB": "Airbnb",
  "ABNd": "ABN Amro",
  "ABX": "Barrick Gold",
  "ADBE": "Adobe",
  "ADSGn": "Adidas",
  "ADYEN": "Adyen",
  "AEGON": "Aegon",
  "AI": "Air Liquide",
  "AIR": "Airbus",
  "AIRF": "Air France-KLM",
  "AIRP": "Air Liquide",
  "ALB": "Albemarle",
  "ALSO": "Alstom",
  "ALV": "Allianz",
  "ALVG": "Allianz",
  "AMD": "AMD",
  "AMPF": "Amplifon",
  "AMZN": "Amazon",
  "ANGLOAMERICAN": "Anglo American",
  "ARM": "Arm",
  "ASML": "ASML",
  "AV": "Aviva",
  "AXA": "AXA",
  "AXAF": "AXA",
  "AXP": "American Express",
  "AZMT": "Azimut",
  "BABA": "Alibaba",
  "BAC": "Bank of America",
  "BAER": "Julius Baer",
  "BAMI": "Banco BPM",
  "BARC": "Barclays",
  "BASFn": "BASF",
  "BAYGn": "Bayer",
  "BBVA": "BBVA",
  "BBY": "Best Buy",
  "BCU": "Brunello Cuccinelli",
  "BE": "Bloom Energy",
  "BHB": "BHB",
  "BIDU": "Baidu",
  "BKNG": "Booking",
  "BLDP": "Ballard",
  "BMPS": "Monte dei Paschi di Siena",
  "BMWG": "BMW",
  "BMY": "Bristol-Myers Squibb",
  "BNPP": "BNP Paribas",
  "BNTX": "BioNTech",
  "BOSSn": "Hugo Boss",
  "BP": "BP",
  "BRBY": "Burberry",
  "BWXT": "BWXT",
  "C": "Citigroup",
  "CAGR": "Credit Agricole",
  "CBKG": "Commerzbank",
  "CCL": "Carnival",
  "CFR": "Richemont",
  "CIGNA": "Cigna",
  "CLF": "Cleveland-Cliffs",
  "COIN": "Coinbase",
  "CONG": "Continental",
  "CPRI": "Capri",
  "CPRI_M": "Campari",
  "CRM": "Salesforce",
  "DAL": "Delta Air Lines",
  "DANO": "Danone",
  "DBKGn": "Deutsche Bank",
  "DHER": "Delivery Hero",
  "DHLn": "Deutsche Post DHL",
  "DIAS": "DiaSorin",
  "DOCU": "DocuSign",
  "EL": "Estée Lauder",
  "ELE": "Endesa",
  "EMII": "Bper Banca",
  "ENEL": "Enel",
  "ENGIE": "Engie",
  "ENI": "Eni",
  "ENPH": "Enphase",
  "ENR1n": "ENR1n",
  "ESLX": "EssilorLuxottica",
  "EXC": "Exelon",
  "EXPE": "Expedia",
  "EZJ": "easyJet",
  "F": "Ford",
  "FBK": "FinecoBank",
  "FCX": "Freeport-McMoRan",
  "FL": "Foot Locker",
  "FSLR": "First Solar",
  "FTMIB": "FTSE MIB",
  "G": "Generali",
  "GAP": "Gap",
  "GDAXI": "DAX",
  "GLEN": "Glencore",
  "GM": "General Motors",
  "GOLD": "Barrick Gold",
  "GOOGL": "Alphabet",
  "HEIN": "Heineken",
  "HMb": "H&M",
  "HPE": "Hewlett Packard Enterprise",
  "HRMS": "Hermès",
  "HSCE": "Hang Seng China Enterprises",
  "HUM": "Humana",
  "IBE": "Iberdrola",
  "IFXGn": "Infineon",
  "ILMN": "Illumina",
  "ING": "ING",
  "INTC": "Intel",
  "ISP": "Intesa Sanpaolo",
  "IVG": "Iveco",
  "JCI": "Johnson Controls",
  "JD": "JD.com",
  "JPM": "JPMorgan",
  "KO": "Coca-Cola",
  "LDOF": "Leonardo",
  "LHAG": "Lufthansa",
  "LI": "Li Auto",
  "LLY": "Eli Lilly",
  "LUMN": "Lumen",
  "LVMH": "LVMH",
  "M9CXWESY": "M9CXWESY",
  "MBGn": "Merck KGaA",
  "MDBI": "Mediobaca",
  "META": "Meta",
  "MICP": "Compagnie Générale des Établissements Michelin",
  "MONC": "Moncler",
  "MRCG": "Merck",
  "MRK": "Merck & Co",
  "MRNA": "Moderna",
  "MSFT": "Microsoft",
  "MSTR": "MicroStrategy",
  "MT": "ArcelorMittal",
  "N225E": "Nikkei 225",
  "NASDAQ": "NASDAQ",
  "NDXG": "Nasdaq 100",
  "NEE": "NextEra",
  "NEM": "Newmont",
  "NESN": "Nestlé",
  "NEXII": "Nexi",
  "NFLX": "Netflix",
  "NKE": "Nike",
  "NOVOb": "Novo Nordisk",
  "NVAX": "Novavax",
  "NVDA": "NVIDIA",
  "ORCL": "Oracle",
  "OREP": "L'Oreal",
  "OXY": "Occidental",
  "P911_p": "Porsche",
  "PATH": "UiPath",
  "PERP": "Pernord Ricard",
  "PFE": "Pfizer",
  "PG": "Procter & Gamble",
  "PIRC": "Pirelli",
  "PLTR": "Palantir",
  "PLUG": "Plug Power",
  "PNDORA": "Pandora",
  "PRTP": "Kering",
  "PRY": "Prysmian",
  "PST": "Poste Italiane",
  "PSTG": "Pure Storage",
  "PUMG": "Puma",
  "PVH": "PVH",
  "PYPL": "PayPal",
  "QCOM": "Qualcomm",
  "RACE": "Ferrari",
  "RBIV": "Reiffeisen Bank",
  "RCOP": "Remy Cointreaur",
  "RENA": "Renault",
  "REP": "Repsol",
  "RHMG": "Rheinmetall",
  "RIVN": "Rivian",
  "RL": "Ralph Lauren",
  "RO": "Roche",
  "ROG": "Roche",
  "RUN": "Sunrun",
  "RWEG": "RWE",
  "SAN": "Santander",
  "SAPG": "SAP",
  "SASY": "Sanofi",
  "SATG": "Sartorius",
  "SD3E": "SD3E",
  "SD3EX": "SD3EX",
  "SEDG": "SolarEdge",
  "SFER": "Salvatore Ferragamo",
  "SGEF": "SGS",
  "SGOB": "Saint-Gobain",
  "SHEL": "Shell",
  "SIEGn": "Siemens",
  "SMCI": "Super Micro",
  "SNAP": "Snap",
  "SOGEN": "Société Générale",
  "SOGN": "Société Générale",
  "SOLCYB35": "SOLCYB35",
  "SPMI": "Saipem",
  "SRG": "Snam",
  "SSMI": "Swiss Market Index",
  "STLAM": "Stellantis",
  "STMPA": "STMicroelectronics",
  "STOXX50E": "Euro Stoxx 50",
  "SX6P": "STOXX Europe 600",
  "SX7E": "STOXX Europe 600 Financials",
  "TEF": "Telefónica",
  "TENR": "Tenaris",
  "TLIT": "Telecom Italia",
  "TPR": "Tapestry",
  "TRIP": "Tripadvisor",
  "TSLA": "Tesla",
  "TSM": "TSMC",
  "TTEF": "TotalEnergies",
  "TUI1n": "TUI",
  "UAA": "Under Armour",
  "UAL": "United Airlines",
  "UBER": "Uber",
  "UBIP": "Ubisoft",
  "UCG": "UniCredit",
  "UHR": "Swatch",
  "UNH": "UnitedHealth",
  "UPS": "UPS",
  "V": "Visa",
  "VERB": "Verb",
  "VIE": "Veolia",
  "VOD": "Vodafone",
  "VOW": "Volkswagen",
  "VOWG": "Volkswagen",
  "VRTX": "Vertex",
  "VUSA": "Vanguard S&P 500",
  "VWS": "Vestas",
  "VZ": "Verizon",
  "WMT": "Walmart",
  "XOM": "Exxon Mobil",
  "ZALG": "Zalando",
  "ZM": "Zoom",
  "h1876": "h1876"
};
